@startuml
class User{
  Int id
  String username
  String nickname
  String avatar_url
}
class Dream{
  String title
  String description
  Array postList
  Array targetList
  Array tierList
}
class Post{
  String title
  String content
  Boolean isMemberOnly
  Array pics
}
class Tier{
  String title
  String description
  String reward
  Number price
}
class Comment{
  String user_id
  String title
  String content
}
User "1" -- "many" Dream
Dream "1" -- "many" Tier
Dream "1" -- "many" Post
Post "many" -- "many" Comment

@enduml