@startuml
:Web;
split
  :Client;
  split
    :React;
    split
      :Redux;
      detach
    split again
      :React-router;
      detach
    split again
      :Antd-mobile;
      detach
    end split
  split again
    :Less;
    detach
  split again
    :History;
    detach
  end split
split again
  :Server;
  split
    :eggjs;
    :sequelize;
    :mysql;
    detach
  split again
    :nginx;
    detach
  end split
end split
@enduml